name: just_tooltip
description: "A lightweight, customizable Flutter tooltip with flexible placement, hover & tap triggers, programmatic control, and RTL support."
version: 0.1.2
homepage: https://github.com/kihyun1998/just_tooltip
repository: https://github.com/kihyun1998/just_tooltip
issue_tracker: https://github.com/kihyun1998/just_tooltip/issues
topics:
  - tooltip
  - overlay
  - popup
  - widget
  - ui

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
